services:
  todo:
    image: postgres:17
    container_name: todo_pgsql_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: todo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: